spring.application.name=infraops-backend

# MongoDB Configuration
# spring.data.mongodb.uri=mongodb://localhost:27017/infraops_db

spring.data.mongodb.uri=mongodb+srv://Vasanth:vasanth0330@cluster0.lcuorrf.mongodb.net/infraops_db?retryWrites=true&w=majority&appName=infraops


spring.data.mongodb.auto-index-creation=true

# JWT Configuration
# A secure 256-bit key for JWT signing. This should be externalized in production.
app.jwt.secret=94a08da1fecbb6e8b46990538c7b50b2848f074d209210c850239243763eb43e
app.jwt.expirationMs=86400000

# App Server Port
server.port=8080
